CONFIG_BSP_USING_ADC1=y
CONFIG_PSRAM_CACHE_WB=y
CONFIG_BSP_USING_SDIO=y
CONFIG_BSP_USING_SDMMC2=y
# CONFIG_BSP_USING_BUILTIN_LCD is not set
CONFIG_EPD_WAVEFORM_USE_BIN=y
CONFIG_RT_MAIN_THREAD_STACK_SIZE=65536
CONFIG_RT_USING_DFS_ELMFAT=y
CONFIG_RT_DFS_ELM_CODE_PAGE=936
CONFIG_RT_SERIAL_RB_BUFSZ=256
CONFIG_RT_USING_HWMAILBOX=y
CONFIG_RT_USING_BLUETOOTH=y
CONFIG_RT_USING_LWIP=y
CONFIG_RT_USING_LWIP212=y
CONFIG_RT_LWIP_TCPTHREAD_MBOX_SIZE=48
CONFIG_RT_LWIP_TCPTHREAD_STACKSIZE=4096
CONFIG_RT_LWIP_USING_MQTT=y
CONFIG_RT_LWIP_USING_WEBSOCKET=y
CONFIG_LWIP_ALTCP=y
CONFIG_LWIP_ALTCP_TLS=y
CONFIG_RT_LWIP_DEBUG=y
CONFIG_RT_USING_RYM=y
CONFIG_RT_USING_ULOG=y
CONFIG_ULOG_LINE_BUF_SIZE=256
CONFIG_ULOG_OUTPUT_FLOAT=y
# CONFIG_ULOG_USING_COLOR is not set
CONFIG_ULOG_OUTPUT_THREAD_NAME=y
CONFIG_RT_USING_MEMHEAP=y
CONFIG_RT_USING_MEMTRACE=y
CONFIG_PKG_USING_NETUTILS=y
CONFIG_PKG_NETUTILS_IPERF=y
CONFIG_PKG_NETUTILS_NTP=y
CONFIG_BSP_USING_FULL_ASSERT=y
CONFIG_BLUETOOTH=y
# CONFIG_NVDS_AUTO_UPDATE_MAC_ADDRESS is not set
CONFIG_BT_FINSH=y
CONFIG_BT_PROFILE_CUSTOMIZE=y
CONFIG_CFG_PAN=y
CONFIG_CFG_HID=y
CONFIG_BT_AUTO_CONNECT_LAST_DEVICE=y
CONFIG_BTS2_APP_MENU=y
CONFIG_USING_BUTTON_LIB=y
CONFIG_BUTTON_MAX_NUM=3
CONFIG_BUTTON_ADV_ACTION_CHECK_DELAY=1000
CONFIG_BSP_USING_PM=y
CONFIG_PKG_USING_CJSON=y
CONFIG_PKG_USING_FLASHDB=y
CONFIG_PKG_FREETYPE=y
CONFIG_PKG_USING_MBEDTLS=y
CONFIG_PKG_USING_MBEDTLS_USE_ALL_CERTS=y
CONFIG_PKG_USING_MBEDTLS_USER_CERTS=y
CONFIG_PKG_USING_WEBCLIENT=y
CONFIG_LCD_USING_EPD_E0470A03_V10_57=y
